apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: read-logs
spec:
  selector:
    matchLabels:
      name: read-logs
  template:
    metadata:
      labels:
        name: read-logs
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        ports:
        volumeMounts:
        - name: varlog
          mountPath: /input
          readOnly: true
        securityContext:

      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          
